
sed -i 's:\/Gn:\/gn:g' *.md
sed -i 's:\/Êx:\/ex:g' *.md
sed -i 's:\/Lv:\/lv:g' *.md
sed -i 's:\/Nm:\/nm:g' *.md
sed -i 's:\/Dt:\/dt:g' *.md
sed -i 's:\/Js:\/js:g' *.md
sed -i 's:\/Jz:\/jz:g' *.md
sed -i 's:\/Rt:\/rt:g' *.md
sed -i 's:\/1Sm:\/1sm:g' *.md
sed -i 's:\/2Sm:\/2sm:g' *.md
sed -i 's:\/1Rs:\/1rs:g' *.md
sed -i 's:\/2Rs:\/2rs:g' *.md
sed -i 's:\/1Cr:\/1cr:g' *.md
sed -i 's:\/2Cr:\/2cr:g' *.md
sed -i 's:\/Ed:\/ed:g' *.md
sed -i 's:\/Ne:\/ne:g' *.md
sed -i 's:\/Et:\/et:g' *.md
sed -i 's:\/Jó:\/jó:g' *.md
sed -i 's:\/Sl:\/sl:g' *.md
sed -i 's:\/Pv:\/pv:g' *.md
sed -i 's:\/Ec:\/ec:g' *.md
sed -i 's:\/Ct:\/ct:g' *.md
sed -i 's:\/Is:\/is:g' *.md
sed -i 's:\/Jr:\/jr:g' *.md
sed -i 's:\/Lm:\/lm:g' *.md
sed -i 's:\/Ez:\/ez:g' *.md
sed -i 's:\/Dn:\/dn:g' *.md
sed -i 's:\/Jl:\/jl:g' *.md
sed -i 's:\/Am:\/am:g' *.md
sed -i 's:\/Jn:\/jn:g' *.md
sed -i 's:\/Mq:\/mq:g' *.md
sed -i 's:\/Os:\/os:g' *.md
sed -i 's:\/Hc:\/hc:g' *.md
sed -i 's:\/Sf:\/sf:g' *.md
sed -i 's:\/Ag:\/ag:g' *.md
sed -i 's:\/Zc:\/zc:g' *.md
sed -i 's:\/Ml:\/ml:g' *.md
sed -i 's:\/Mt:\/mt:g' *.md
sed -i 's:\/Mc:\/mc:g' *.md
sed -i 's:\/Lc:\/lc:g' *.md
sed -i 's:\/Jo:\/jo:g' *.md
sed -i 's:\/At:\/atos:g' *.md
sed -i 's:\/At:\/atos:g' *.md
sed -i 's:\/Rm:\/rm:g' *.md
sed -i 's:\/1Co:\/1co:g' *.md
sed -i 's:\/2Co:\/2co:g' *.md
sed -i 's:\/Gl:\/gl:g' *.md
sed -i 's:\/Ef:\/ef:g' *.md
sed -i 's:\/Fp:\/fp:g' *.md
sed -i 's:\/Cl:\/cl:g' *.md
sed -i 's:\/1Ts:\/1ts:g' *.md
sed -i 's:\/2Ts:\/2ts:g' *.md
sed -i 's:\/1Tm:\/1tm:g' *.md
sed -i 's:\/2Tm:\/2tm:g' *.md
sed -i 's:\/Tt:\/tt:g' *.md
sed -i 's:\/Hb:\/hb:g' *.md
sed -i 's:\/Tg:\/tg:g' *.md
sed -i 's:\/1Pe:\/1pe:g' *.md
sed -i 's:\/2Pe:\/2pe:g' *.md
sed -i 's:\/1Jo:\/1jo:g' *.md
sed -i 's:\/Ap:\/ap:g' *.md
